autocmd.ts
deps.ts
execute.ts
mod.ts
variable.ts
vim.ts

Initial impl

---

deps.ts

Update denops to fix massive data issue

---

deps.ts
vim/vim.ts

Use https://deno.land/x/denops_core@v0.10.0 instead

Use `denops_core` module instead

---

vim/vim.ts

Refactoring

---

deps.ts
vim/load.ts
vim/mod.ts
vim/vim.ts

The original version was proposed on #14 by @higashi000

Add `load()` to source local/remote Vim script

---

README.md
deps.ts
deps_test.ts
mod.ts
vim/execute.ts
vim/vim.ts

Update deps to latest

---

README.md

Apply deno fmt

---

.github/workflows/test.yml

Ref: https://github.com/vim-denops/denops.vim/pull/49
Added a job to do type checking in CI.

Add type check to CI

---

vim/function.ts

I want to use these functions.

Add some functions

---

vim/function.ts

Add `setline` `setbufline` and fix arguments definition of some functions.

Add some funtions

---

.github/workflows/test.yml
Makefile
autocmd/common.ts
autocmd/common_test.ts
autocmd/group.ts
autocmd/group_test.ts
deps.ts
function/buffer.ts
function/common.ts
helper/execute.ts
helper/load.ts
modules-lock.json
modules.json
test/mod.ts
variable/helper.ts
variable/helper_test.ts
vendor/https/deno.land/std/fs/mod.ts
vendor/https/deno.land/std/hash/mod.ts
vendor/https/deno.land/std/path/mod.ts
vendor/https/deno.land/std/testing/asserts.ts
vendor/https/deno.land/x/denops_core/mod.ts
vendor/https/deno.land/x/denops_core/test/mod.ts
vendor/https/deno.land/x/unknownutil/mod.ts

https://github.com/keroxp/dlink

☕  Use dlink to manage dependencies

---

.github/workflows/test.yml

See also https://github.com/vim-denops/denops.vim/commit/74e5896f6ecf4850e40f518a6cb56276c8f9a148

☕  Rewrite GitHub Action workflow for deno

---

.github/workflows/test.yml

🚿  Reduce the number of jobs in CI

---

denops_std/function/buffer.ts
denops_std/function/common.ts
denops_std/helper/execute_test.ts

Minor improvements

---

denops_std/function/_generated.ts
denops_std/function/nvim/_generated.ts
denops_std/function/vim/_generated.ts
scripts/gen-function/format.ts

Fix `gen-function`

---

denops_std/deps.ts
denops_std/deps_test.ts

📦  Update denops_core to v1.0.0-beta.3

---

denops_std/function/buffer.ts

Fix arguments of `fn.bufnr()`

---

denops_std/function/buffer.ts
denops_std/function/common.ts

Change argument names of functions to based on vim's help

Change argument names of some functions

---

denops_std/function/buffer.ts
denops_std/function/common.ts

:shower: Remove check `undefined` in functions

---

denops_std/function/_generated.ts
denops_std/function/nvim/_generated.ts
denops_std/function/vim/_generated.ts
scripts/gen-function/parse.ts

🐛 Accept optional first parameter in generation

---

denops_std/function/_generated.ts
denops_std/function/_manual.ts
denops_std/function/various.ts
denops_std/function/various_test.ts

👍Correct type of `mode()`

---

denops_std/helper/echo.ts
denops_std/helper/echo.vim

Close #77 
https://user-images.githubusercontent.com/546312/129470028-5e8dcad3-6979-4018-870a-2c4189046a1f.mp4
https://user-images.githubusercontent.com/546312/129470042-1c67ff3e-da1e-48d5-b3d6-2a56078a22cf.mp4

:bug: Fix flush on `echo()` function in `helper` module on Vim

---

denops_std/function/nvim/_generated.ts
scripts/gen-function/format.ts
scripts/gen-function/gen-function.ts
scripts/gen-option/format.ts

:+1: Add `nvim_` functions of Neovim in `function/nvim` module

---

denops_std/mapping/README.md
denops_std/mapping/mod.ts
denops_std/mapping/mod_test.ts

:+1: Support array `mode` for `map()` and `unmap()` in `mapping` module

---

denops_std/helper/load.ts
denops_std/helper/load_test.ts
denops_std/helper/load_test.vim

issues: #75 
add load function test.
It is expected test will faile.
Because, it is not exist Vim script file in main branch.

Add load() test

---

denops_std/helper/input.ts

:bug: Do NOT use `once` for completion function of `input`

---

denops_std/helper/README.md
denops_std/helper/load.ts

:+1: Do NOT reload Vim script files on `load()`

---

denops_std/function/input.ts
denops_std/helper/input.ts

https://nanto.asablo.jp/blog/2021/09/11/9422241
https://github.com/sindresorhus/type-fest

:bug: Fix type definitions of `completion` argument

---

denops_std/deps.ts
denops_std/deps_test.ts

Fix Deno 1.11.0 support

---

.github/workflows/test.yml

https://docs.github.com/ja/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idservicesservice_idenv

:coffee: Fix GHA filter pattern

---

denops_std/deps.ts
denops_std/deps_test.ts

:package: Update deps

---

.github/workflows/test.yml
Makefile
denops_std/deps.ts
denops_std/deps_test.ts

SSIA
https://github.com/vim-denops/denops.vim/pull/169

Follow denops v3

---

denops_std/helper/README.md
denops_std/helper/echo.ts

Add `echoerr` and `friendlyCall` to `helper` module.

---

denops_std/batch/README.md
denops_std/function/README.md
denops_std/helper/README.md
denops_std/option/README.md
denops_std/variable/README.md

:herb: Fix type checks on READMEs

---

denops_std/function/vim/_generated.ts
scripts/gen-function/format.ts
scripts/gen-function/gen-function.ts

Add Vim specific missing functions to `function/vim`

---

denops_std/buffer/buffer.ts
denops_std/buffer/buffer_test.ts
denops_std/buffer/decoration.ts

:muscle: Use relative imports instead

---

denops_std/autocmd/group.ts
denops_std/batch/batch.ts
denops_std/batch/gather.ts
denops_std/buffer/buffer.ts
denops_std/helper/README.md
denops_std/helper/echo.ts

:bug: Fix behavior of `helper.echo/echoerr` and add a way to silence messages

---

Makefile
denops_std/buffer/README.md
denops_std/buffer/buffer.ts
denops_std/buffer/buffer_test.ts
denops_std/buffer/mod.ts

It is kinda breaking change but the public exports was not documented thus we'll release this changes as MINOR change rather than MAJOR unless someone argue with that.

:boom: Remove undocumented public exports and add some features on `buffer` module

---

README.md
denops_std/function/_generated.ts
denops_std/function/nvim/_generated.ts
denops_std/function/vim/_generated.ts
denops_std/option/_generated.ts
denops_std/option/nvim/_generated.ts
denops_std/option/vim/_generated.ts
scripts/gen-function/format.ts
scripts/gen-function/gen-function.ts
scripts/gen-function/parse.ts
scripts/gen-option/gen-option.ts

We've totally forgot to update those 😅 
It should had happened at https://github.com/vim-denops/deno-denops-std/pull/117

:+1: Update target Vim/Neovim versions of `function` and `option` modules

---

denops_std/buffer/decoration.ts

:bug: Fix `decoration` module on Vim

---

denops_std/mapping/parser.ts
denops_std/mapping/parser_test.ts
denops_std/mapping/types.ts

:bug: Fix `Failed to parse a mapping record` issue

---

denops_std/mapping/mod.ts
denops_std/mapping/parser_test.ts

:bug: Fix parse error on "Nvim builtin"

---

denops_std/buffer/buffer.ts

For https://github.com/vim-denops/denops.vim/pull/214

:bug: Fix `buffer` module on reconnection

---

denops_std/helper/load.ts

:muscle: Use web crypto API instead of deprecated std/hash

---

denops_std/function/vim/_generated.ts
denops_std/function/vim/_manual.ts
denops_std/function/vim/prop_add_list.ts

:bug: Fix `prop_add_list` function on Vim

---

denops_std/function/_generated.ts
denops_std/function/_manual.ts
denops_std/function/getreginfo.ts

:+1: Add a workaround for `getreginfo` in Vim

---

denops_std/buffer/README.md
denops_std/buffer/decoration.ts

:+1: Allow to specify range to undecorate()

---

denops_std/option/_generated.ts
denops_std/option/nvim/_generated.ts
denops_std/option/vim/_generated.ts
scripts/gen-option/format.ts
scripts/gen-option/parse.ts
scripts/gen-option/types.ts

Closes #183 
With refactoring.
Added type `OptionType` and `OptionScope` to make it more robust.

Fix options parse

---

denops_std/batch/batch.ts
denops_std/helper/input.ts

:+1: Use lambda instead of anonymous

---

denops_std/buffer/buffer.ts

:muscle: Use `collect()` instead of `gather()`

---

denops_std/option/_generated.ts
denops_std/option/_generated_test.ts
denops_std/option/nvim/_generated.ts
denops_std/option/vim/_generated.ts
scripts/gen-option/format.ts

:bug: Fix option `setBuffer()` and `setWindow()` replace the option value

---

denops_std/variable/types.ts

💪 Use type instead of interface (close #206)

---

denops_std/option/_generated.ts
denops_std/option/nvim/_generated.ts
denops_std/option/types.ts
denops_std/option/vim/_generated.ts
scripts/gen-option/format.ts

Add interface types to individual options.
- Clarify the definition of each option.
- Added JSDoc for the method.

:+1: Add option interface

---

denops_std/option/_generated.ts
denops_std/option/_generated_test.ts
denops_std/option/nvim/_generated.ts
denops_std/option/vim/_generated.ts
scripts/gen-option/format.ts

Fixes #203.
This PR based on #202.

:bug: Fix boolean option getter returns true|false instead 1|0 

---

.github/workflows/test.yml
.gitignore
README.md
deno.jsonc
denops_std/README.md

:coffee: Add code coverage

---

.scripts/gen-function/gen-function.ts
function/_generated.ts

Add functions to manipulate signs like "sign_define", "sign_place" and etc.

Add sign functions

---

deno.jsonc
scripts/gen-option/parse.ts

:coffee: Fix lint

---

deno.jsonc

Do not publish unnecessary files:
- Dot files
- Test files
- README.md in sub-directory

:coffee: fix publish files

---

buffer/buffer.ts
buffer/fileformat.ts
buffer/mod.ts
deno.jsonc
function/types.ts
helper/expr_string.ts
helper/input.ts
helper/keymap.ts

:package: Update unknownutil v4
