vim-denops/deno-denops-std

vim/variable.ts
vim/vim.ts

1. Remove 'env' type which is quite different from others
2. Add `defaultValue` argument to fix behavior difference between Vim/Neovim (#5)

Fix behavior of 'variables' module

---

deps.ts
deps_test.ts
main.ts
mod.ts
vim/vim.ts

Now `start()` become deprecated and new `main()` is added. Plugin developers should use `main()` like:
```typescript
import { main } from "https://deno.land/x/denops_std/mod.ts";
main(async ({ vim }) => {
// ...
});
```
Because the first argument become a context object, any named attributes are easily added in future like:
```typescript
import { main } from "https://deno.land/x/denops_std/mod.ts";
main(async ({ vim, denops }) => {
// Call other plugin's API through `denops` instance
await denops.dispatch(...);
// ...
});
```
Wait for https://github.com/vim-denops/denops.vim/pull/33 and new release.

Add 'main()' and deprecate 'start()'

---

.github/workflows/test.yml
deps.ts
test.ts
vim/variable_test.ts

Denops v0.16.0 supports testing with denops thus I've added example test.

Add tests for `variable` module as test writing example

---

.github/workflows/test.yml

Otherwise `deno test` tests all ts files in `denops.vim` as well.

Separate repository checkout path and denops.vim

---

denops_std/anonymous/mod.ts
denops_std/anonymous/mod_test.ts

Close https://github.com/vim-denops/denops.vim/issues/48 by `anonymous` module like:
```typescript
test({
mode: "all",
name: "add() registers anonymous functions",
fn: async (denops) => {
const ids = anonymous.add(
denops,
() => Promise.resolve("0"),
() => Promise.resolve("1"),
() => Promise.resolve("2"),
);
assertEquals(await denops.dispatch(denops.name, ids[0]), "0");
assertEquals(await denops.dispatch(denops.name, ids[1]), "1");
assertEquals(await denops.dispatch(denops.name, ids[2]), "2");
assertEquals(await denops.dispatch(denops.name, ids[0]), "0");
assertEquals(await denops.dispatch(denops.name, ids[1]), "1");
assertEquals(await denops.dispatch(denops.name, ids[2]), "2");
},
});
test({
mode: "all",
name: "once() registers oneshot anonymous functions",
fn: async (denops) => {
const …
```

Add `anonymous.ts` to help registering anonymous functions

---

denops_std/helper/batch.ts
denops_std/helper/batch_test.ts
denops_std/helper/mod.ts
denops_std/modules-lock.json
denops_std/modules.json
denops_std/vendor/https/deno.land/x/denops_core/mod.ts
denops_std/vendor/https/deno.land/x/denops_core/test/mod.ts

With this PR, users can use `denops.cmd()`, `denops.eval()`, `function` module, or whatever which require `denops` instance to perform batch process like:
```typescript
const results = await batch(denops, (helper) => {
helper.cmd("DoSomething");
helper.eval("1 + 1");
fn.range(helper, 2);
});
assertEquals(results, [0, 2, [0, 1]);
```
It's a wrapper function of `denops.batch()`.

Add `batch` module to perform batch process

---

denops_std/function/buffer.ts

Fixed calling when end was undefined.

:bug: Fix fn.getbufline.

---

denops_std/deps.ts
denops_std/helper/README.md
denops_std/helper/echo.ts
denops_std/helper/echo_test.ts

Use `echo()` to show messages on the cmdline area. It is required while Vim won't show messages reported from channel commands and it won't pause multi-line messages reported from asynchronous context (e.g. timer or job). It's same for `denops.cmd('echo "Hello\nWorld!"')` in Neovim.
Note that there is no similar function for `echomsg` while there is no way to properly show multi-line messages with `echomsg` from asynchronous context.
```typescript
import { Denops } from "https://deno.land/x/denops_std/mod.ts";
import { echo } from "https://deno.land/x/denops_std/helper/mod.ts";
export async function main(denops: Denops): Promise<void> {
await echo(denops, "Hello\nWorld!");
}
```

👍  Add `echo` function to `helper` module

---

denops_std/deps.ts
denops_std/deps_test.ts
denops_std/function/_generated.ts
denops_std/function/_manual.ts
denops_std/function/cursor.ts
denops_std/function/cursor_test.ts
denops_std/function/types.ts

Rewrite of #62
Add type definition for below Vim script functions for #44.
- `col()`
- `virtcol()`
- `line()`
- `wincol()`
- `winline()`
- `cursor()`
- `screenpos()`
- `getcurpos()`
- `getpos()`
- `setpos()`
- `byte2line()`
- `line2byte()`
- `diff_filler()`
And add types for some function result.

👍 Add Type Definitions for cursor-functions

---

denops_std/batch/README.md
denops_std/batch/batch.ts
denops_std/batch/batch_test.ts
denops_std/batch/gather.ts
denops_std/batch/gather_test.ts
denops_std/batch/mod.ts
denops_std/helper/README.md
denops_std/helper/batch.ts

The previous `batch` could not be nested thus I add a new `batch` module with two functions
- `batch` is used to perform multiple operations sequentially without the overhead. This function can be nested but it does not return results
- `gather` is used to get results of multiple sequential operations without the overhead. This function cannot be nested.

Add `batch` module to handle `denops.batch` more flexibly

---

denops_std/mapping/README.md
denops_std/mapping/mod.ts
denops_std/mapping/mod_test.ts
denops_std/mapping/parser.ts
denops_std/mapping/parser_test.ts
denops_std/mapping/types.ts

SSIA
```typescript
import { Denops } from "https://deno.land/x/denops_std/mod.ts";
import * as mapping from "https://deno.land/x/denops_std/mapping/mod.ts";
export async function main(denops: Denops): Promise<void> {
await mapping.map(denops, "<Plug>(test-denops-std)", "Hello");
await mapping.map(denops, "<Plug>(test-denops-std)", "Hello", {
mode: "i",
});
console.log(await mapping.read(denops, "<Plug>(test-denops-std)"));
// {
//   mode: "",
//   lhs: "<Plug>(test-denops-std)",
//   rhs: "Hello",
//   // ...
// }
const result = await mapping.list(denops, "<Plug>");
console.log(result);
// [
//   {
//     mode: "",
//     lhs: "<Plug>(...)",
//     // ...
//   },
//   // ...
// ]
await mapping.unmap(denops, "<Plug>(test-denops-std)");
await mapping.unmap(denops, "<Plug>(test-denops-std)", …
```

👍  Add `mapping` module to manage mappings

---

.github/workflows/test.yml
denops_std/deps.ts
denops_std/deps_test.ts
denops_std/function/_generated.ts
denops_std/function/vim/_generated.ts
denops_std/option/_generated.ts
denops_std/option/vim/_generated.ts
scripts/gen-function/gen-function.ts
scripts/gen-option/gen-option.ts

While denops.vim itself drop support Vim before 8.2.0662 (https://github.com/vim-denops/denops.vim/pull/97)

:boom: Drop support vim before 8.2.0662

---

denops_std/batch/README.md
denops_std/batch/batch.ts
denops_std/batch/batch_test.ts
denops_std/batch/gather.ts
denops_std/batch/gather_test.ts

1. `BatchHelper` instance is available outside of the `batch` block and works like a real `denops` instance
2. `GatherHelper` instance is NOT available outside of the `gather` block and errors are thrown

:+1: Define behaviors of BatchHelper/GatherHelper instances outside of the block

---

denops_std/helper/input.vim

:bug: Do NOT use temporary buffer in `input()` on Vim

---

denops_std/README.md
denops_std/bufname/README.md
denops_std/bufname/bufname.ts
denops_std/bufname/bufname_test.ts
denops_std/bufname/mod.ts
denops_std/bufname/utils.ts
denops_std/bufname/utils_test.ts
denops_std/deps.ts
denops_std/deps_test.ts
denops_std/helper/load_test.ts

Use `format()` to format a Vim's buffer name in a safe way from `Bufname` instance like:
```typescript
import { assertEquals } from "https://deno.land/std/testing/asserts.ts";
import { Denops } from "https://deno.land/x/denops_std/mod.ts";
import { format } from "https://deno.land/x/denops_std/bufname/mod.ts";
export async function main(denops: Denops): Promise<void> {
assertEquals(
format({ scheme: "denops", path: "/Users/johntitor/.vimrc" }),
"denops:///Users/johntitor/.vimrc",
);
assertEquals(
format({
scheme: "denops",
path: "/Users/johntitor/.vimrc",
params: {
foo: "foo",
bar: ["bar", "bar"],
hoge: undefined,
},
}),
"denops:///Users/johntitor/.vimrc;foo=foo&bar=bar&bar=bar",
);
assertEquals(
format({
scheme: "denops",
path: "/Users/johntitor/.vimrc",
params: {
foo: "foo",
bar: …
```

:+1: Add `bufname` module

---

denops_std/bufname/README.md
denops_std/bufname/bufname.ts
denops_std/bufname/bufname_test.ts
denops_std/bufname/mod.ts
denops_std/bufname/utils.ts
denops_std/bufname/utils_test.ts
scripts/gen-function/parse.ts
scripts/gen-option/parse.ts

This PR includes the following breaking change
- Rename `path` attribute to `expr` in `Bufname`

:boom: Improve `bufname` module (with breaking changes)

---

denops_std/anonymous/mod_test.ts
denops_std/batch/gather_test.ts
denops_std/deps.ts
denops_std/deps_test.ts
denops_std/function/input_test.ts
denops_std/helper/execute_test.ts
denops_std/helper/input_test.ts
denops_std/helper/load_test.ts
denops_std/mapping/mod_test.ts
denops_std/variable/register_test.ts

The output of `make update` is
```
./denops_std/bufname/mod.ts
./denops_std/bufname/utils.ts
./denops_std/bufname/bufname_test.ts
./denops_std/bufname/utils_test.ts
./denops_std/bufname/bufname.ts
./denops_std/anonymous/mod.ts
./denops_std/anonymous/mod_test.ts
./denops_std/mod.ts
./denops_std/deps.ts
[1/6] Looking for releases: https://deno.land/std@0.113.0/fs/mod.ts
[1/6] Attempting update: https://deno.land/std@0.113.0/fs/mod.ts -> 0.119.0
[1/6] Update successful: https://deno.land/std@0.113.0/fs/mod.ts -> 0.119.0
[2/6] Looking for releases: https://deno.land/std@0.113.0/hash/mod.ts
[2/6] Attempting update: https://deno.land/std@0.113.0/hash/mod.ts -> 0.119.0
[2/6] Update successful: https://deno.land/std@0.113.0/hash/mod.ts -> 0.119.0
[3/6] Looking for releases: …
```

:package: Update Deno dependencies

---

denops_std/buffer/buffer.ts

It seems changing `fileformat` or `fileencoding` cause E21 when `modifiable` is off.

:bug: Ensure `modifiable` in `assign`

---

denops_std/buffer/README.md
denops_std/buffer/buffer.ts
denops_std/buffer/buffer_test.ts

It's important to call `win_getid()` or whatever synchronously to make sure that the current buffer is what we assumed. That's why we improved the functionality of `buffer.open()` to return those result.

:+1: Improve `buffer.open()` functionality

---

.github/workflows/test.yml
denops_std/bufname/README.md
denops_std/bufname/bufname.ts
denops_std/bufname/bufname_test.ts
denops_std/bufname/utils.ts
denops_std/bufname/utils_test.ts

Parsing a buffer name like `ginlog:///Users/alisue/ghq/github.com/lambdalisue/gin.vim;pretty=%22%25C%28yellow%29%25h%25C%28reset%29+%25C%28magenta%29%5B%25ad%5D%25C%28reset%29%25C%28auto%29%25d%25C%28reset%29+%25s+%25C%28cyan%29%40%25an%25C%28reset%29%22#[]$` throws `URI malformed` error. This PR fix that issue.

:bug: Fix "URI malformed" error on `bufname` module when a `expr` contains percent encoded characters

---

.github/workflows/test.yml
.github/workflows/udd.yml

To avoid Node.js 12 actions are deprecated warnings

:coffee: Upgrade `action/cache` to v3

---

denops_std/helper/execute.ts
denops_std/helper/execute_test.ts

- Bug fix:
- Only trim start of line, because trailing space is necessary in some cases.
- Improve:
- Do not call self recursively.
- Returns a `Promise` directly instead using await.

:bug: Fix trailing spaces capable in `execute()`

---

denops_std/helper/echo.ts
denops_std/helper/echo_test.ts

Since `echo` runs asynchronously, we need to runs `echohl` as well.

:bug: Fix `echoerr`

---

denops_std/function/buffer.ts
denops_std/function/common.ts
denops_std/function/cursor.ts
denops_std/function/cursor_test.ts
denops_std/function/getreginfo.ts
denops_std/function/input.ts
denops_std/function/various.ts
denops_std/function/vim/prop_add_list.ts

#44
The minimum version supported by denops.vim has been raised, resulting in changes to the type definitions and documentation for some functions. 
This PR is a update of the type definitions and documentation for those functions that were already typed.

Update type definition for `function`

---

denops_std/function/buffer.ts
denops_std/function/common.ts
denops_std/function/cursor.ts
denops_std/function/getreginfo.ts
denops_std/function/input.ts
denops_std/function/various.ts
denops_std/function/vim/prop_add_list.ts
scripts/gen-function/format.ts
scripts/gen-function/gen-function.ts
scripts/gen-function/override.ts
scripts/gen-function/transform.ts
scripts/gen-function/types.ts
scripts/gen-option/format.ts
scripts/gen-option/gen-option.ts
scripts/gen-option/override.ts
scripts/gen-option/transform.ts
scripts/gen-option/types.ts
scripts/transform.ts

Closes #187
Generate JSDoc for functions exported in `_manual.ts`.
💪 Since `has()` referred to nvim help, so now possible to define refer to which help in common functions.
😢 Note that I tried replacing with AST parsing, but gave up because it doesn't preserve formatting.
😄 However, the source files should be `fmt`'d, so there shouldn't be any problems with RegExp parsing.

☕ Generate manual docs

---

denops_std/function/_generated.ts
denops_std/function/nvim/_generated.ts
denops_std/function/vim/_generated.ts
scripts/gen-function/format.ts
scripts/gen-function/gen-function.ts
scripts/gen-function/parse.ts
scripts/gen-function/types.ts

Generate return types by parsing `builtin-function-list`.
I have not checked the correctness of each of the generated types.
But feel LGTM.

Generate return type

---

denops_std/function/buffer.ts

Refs #44
Added following types for arguments of buffer-function.
```typescript
export type BufExistsArg = string | number;
export type BufNameArg = string | number;
export type BufLnumArg = "$" | number;
```
It makes the meaning of the argument types easier to understand.

:+1: Refine argument types for `buffer-function`

---

denops_std/batch/collect.ts
denops_std/batch/collect_test.ts
denops_std/batch/mod.ts

The `batch.gather()` always returns `Promise<unknown[]>` but `batch.collect()` returns properly typeed array.
Use it like
```typescript
import { Denops } from "../mod.ts";
import { collect } from "./collect.ts";
export async function main(denops: Denops): Promise<void> {
const results = await collect(denops, (denops) => [
denops.eval("&modifiable"),
denops.eval("&modified"),
denops.eval("&filetype"),
]);
// results contains the value of modifiable, modified, and filetype
}
```

:+1: Add type-safe `batch.collect()` function

---

.github/workflows/test.yml
denops_std/option/_generated.ts
denops_std/option/nvim/_generated.ts
denops_std/option/vim/_generated.ts
scripts/gen-option/format.ts

Now local options has following new methods
- `getBuffer(denops: Denops, bufnr: number, name: string): Promise<T>`
- `setBuffer(denops: Denops, bufnr: number, name: string, value: T): Promise<void>`
- `getWindow(denops: Denops, winnr: number, name: string): Promise<T>`
- `setWindow(denops: Denops, winnr: number, name: string, value: T): Promise<void>`
Use those to access options on the particular buffer or window.

:+1: Add `getBuffer/setBuffer/getWindow/setWindow` to local options

---

denops_std/variable/environment.ts
denops_std/variable/option.ts
denops_std/variable/register.ts
denops_std/variable/types.ts
denops_std/variable/variable.ts

- Add JSDoc to variable interfaces.
- JSDoc written in the implementation is not referenced from LSP etc.
- Add JSDoc to shorthand properties.

:memo: Add JSDoc to variable

---

.scripts/gen-function/gen-function.ts
function/nvim/_generated.ts
function/vim/_generated.ts

The following functions are added
- `popup_atcursor`
- `popup_beval`
- `popup_clear`
- `popup_close`
- `popup_create`
- `popup_dialog`
- `popup_filter_menu`
- `popup_filter_yesno`
- `popup_findecho`
- `popup_findinfo`
- `popup_findpreview`
- `popup_getoptions`
- `popup_getpos`
- `popup_hide`
- `popup_list`
- `popup_locate`
- `popup_menu`
- `popup_move`
- `popup_notification`
- `popup_setoptions`
- `popup_settext`
- `popup_show`

:+1: Add functions in `popup.txt` for Vim

---

lambda/mod.ts

Improved English wording and added documentation for undocumented public APIs in the `lambda` module.

:memo: Improve documentation for lambda module
